// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenterApi.Models;

#nullable disable

namespace dotnet_backend.Migrations
{
    [DbContext(typeof(VenterApiContext))]
    [Migration("20230103052321_NullableFields2")]
    partial class NullableFields2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VenterApi.Models.Conflict", b =>
                {
                    b.Property<int>("ConflictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApologyStatement")
                        .HasColumnType("longtext");

                    b.Property<string>("ConflictDate")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Feeling")
                        .HasColumnType("longtext");

                    b.Property<string>("Need")
                        .HasColumnType("longtext");

                    b.Property<string>("NeedsStatement")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .HasColumnType("longtext");

                    b.HasKey("ConflictId");

                    b.ToTable("Conflicts");
                });
#pragma warning restore 612, 618
        }
    }
}
